version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  task_manager:
    build:
      dockerfile: ./src/Dockerfile
    hostname: task_manager
    ports:
      - 3000:3000
    networks:
      test_net:
        ipv4_address: 192.168.56.4

networks:
  test_net:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 192.168.56.0/24
         gateway: 192.168.56.1