version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
      POSTGRES_DB: "${POSTGRES_DBNAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      test_net:
        ipv4_address: "${POSTGRES_HOST}"

  task_manager:
    env_file: .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    hostname: task_manager
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    networks:
      test_net:
        ipv4_address: 192.168.56.5

  external_service:
    build:
      context: ./tests/external_service
      dockerfile: ./Dockerfile
    hostname: task_manager
    networks:
      test_net:
        ipv4_address: 192.168.56.4

networks:
  test_net:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 192.168.56.0/24
         gateway: 192.168.56.1