version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      test_net:
        ipv4_address: 192.168.56.2

  task_manager:
    env_file: ".env_test"
    depends_on:
      - postgres
      - external_service
    build:
      context: ./src
      dockerfile: ./Dockerfile
    hostname: task_manager
    networks:
      test_net:
        ipv4_address: 192.168.56.3

  external_service:
    build:
      context: ./external_service
      dockerfile: ./Dockerfile
    hostname: task_manager
    networks:
      test_net:
        ipv4_address: 192.168.56.4

  postman:
    depends_on:
      - task_manager
    build:
      context: ./tests
      dockerfile: ./Dockerfile
    hostname: postman
    networks:
      test_net:
        ipv4_address: 192.168.56.5

networks:
  test_net:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 192.168.56.0/24
         gateway: 192.168.56.1