package env

const (
	EXTERNAL_WEBSERIVCE_URL = "EXTERNAL_WEBSERIVCE_URL"
	POSTGRES_HOST           = "POSTGRES_HOST"
	POSTGRES_USER           = "POSTGRES_USER"
	POSTGRES_PASSWORD       = "POSTGRES_PASSWORD"
	POSTGRES_DBNAME         = "POSTGRES_DBNAME"
	POSTGRES_PORT           = "POSTGRES_PORT"
	SERVICE_PORT            = "SERVICE_PORT"
	LOG                     = "LOG"
)

const (
	LOG_DEBUG = "DEBUG"
	LOG_INFO  = "INFO"
)
